title: Belle's Bookshelf
description: My reading life — Read, TBR, and DNF.
url: "https://lilacbelle.github.io/" # fill after Pages gives you your URL, e.g. https://username.github.io/book-blog
baseurl: "/book-blog" # keep empty if deploying at root
timezone: Asia/Bahrain
theme: minima

# Collections for books
collections:
  books:
    output: true
    permalink: /books/:title/

# Defaults = a “template” for new books
defaults:
  - scope:
      path: ""
      type: books
    values:
      layout: book
      status: tbr   # options: read, tbr, dnf
      rating: 0
      audiobook: false
      genre: []
      tropes: []
      warnings: []
      pages: 0
      started: ""   # e.g., 2025-08-10
      finished: ""  # e.g., 2025-08-14
      recommend: "" # yes/no + why

# Navigation
nav:
  - title: Home
    url: /
  - title: Bookshelf
    url: /bookshelf/
  - title: Read
    url: /read/
  - title: TBR
    url: /tbr/
  - title: DNF
    url: /dnf/
  - title: About
    url: /about/

# Minima options
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/YOUR_USERNAME" }

# Controls top navigation order for Minima
header_pages:
  - index.md
  - bookshelf.md
  - read.md
  - tbr.md
  - dnf.md
  - about.md
